### ISSUE TITLE
Some configs doesn´t seem to work

### ISSUE THREAD

**Issue by heusmich** [mschnitzer/ark-survival-ascended-linux-container-image#24] opened 2023-11-14 21:52 UTC
Hi,

I noticed that some of the configs from my GameUserSettings.ini don´t seem to work.

For example the taming speed, I set the config **TamingSpeedMultiplier=3** in GUS.ini but it doesn´t seem to work.
Today I tamed an Argentavis with level 162 with prime meat, Dododex says that it will take ca. 24 minutes but it took nearly an hour.

Also I changed the day time and night time to make the day longer (**DayTimeSpeedScale=0.919629630**) and the night shorter (**NightTimeSpeedScale=1.241111111**).
This also doesn´t seem to work, I didn´t take the time but my feeling was that day and night were nearly the same.

Not sure if some other configs also doesn´t work, but I noticed these two so far.

Do you know if this could be a problem with the container or with the config?
In ARK - Survival Evolved these settings worked.

Best regards
heusmich

**Comment by mschnitzer** [comment] 2023-11-14 21:55
There are some settings that do not work in ASA at the moment (e.g. DinoCountMultiplier). As for Day/NightTimeSpeedScale, I don't have any info on that, but what I can say is that the taming speed multiplier definitely work, as I adjusted it on my server.

Please attach your `GameUserSettings.ini` and `Game.ini` file to this issue, but remove all passwords from these files. Furthermore, what are the permissions of these files? Is it `root:root` or `25000:25000` ?

**Comment by heusmich** [comment] 2023-11-14 22:12
[Game.txt](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/files/13357708/Game.txt)
[GameUserSettings.txt](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/files/13357710/GameUserSettings.txt)

I had to rename the files to *.txt since it doesn´t seem to be possible to upload ini files.
The owner of the files is 25000.

**Comment by mschnitzer** [comment] 2023-11-14 22:29
I checked my `GameUserSettings.ini` and the tame speed on my server is set to 3x as well and it works. I didn't notice any significant changes that I made in comparison to yours. So not sure where the problem is.

I don't see any connection to the docker image, as the image itself is not dealing with config files in any way, these are being touched by the ASA server software, so the issue must be somewhere else. Asking the obvious: Did you really restart the server and did you make sure your prime meat didn't spoil in the meantime?

Also you can run `showmyadminmanager` as a console command (once you authorized yourself as admin using `enablecheats your_admin_pw` obviously) to bring up the admin control panel which shows you the effective settings on the left side in a box.

**Comment by heusmich** [comment] 2023-11-14 22:38
In the admin manager ingame I can see that the taming speed is 3.0, so this is correct.
Yes, I restarted the server a few times already.
The prime meat didn´t spoil, I put more than 50 prime meat in the Argi and when it was finished there were a lot left.

**Comment by mschnitzer** [comment] 2023-11-14 22:49
If the ingame admin manager is telling you that the tame speed is set to 3.0, then it is 3.0. I'd say just try it again. Maybe you modified the food drain multiplier as well, which has an influence on the taming speed?

**Comment by mschnitzer** [comment] 2023-11-14 22:52
I just realized you sent the configs, so I quickly checked it and it says `DinoCharacterFoodDrainMultiplier=0.5`, which would double the taming time essentially. So an Argi level 162 in your case does not just take 24:46 minutes, but 49:31. The food drain speed can be configured in Dododex as well, next to taming speed.

**Comment by heusmich** [comment] 2023-11-14 23:00
OK, I changed it to 1 again and will check it tomorrow.

Until then maybe another question:
In the logs that I can open with **docker logs -f asa-server-1** I found some error messages, maybe you can tell me if they need to be fixed or not.

**Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory**
**CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.**
**Failed to read /etc/machine-id, error Invalid argument.**
**wine: RLIMIT_NICE is <= 20, unable to use setpriority safely**

Maybe you know them and can tell me how to solve them...

**Comment by mschnitzer** [comment] 2023-11-14 23:21
> Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory

Expected and can be ignored. The exact root cause is not known to me, but it's not needed for steamcmd to operate on that level. Receiving this error in my UE5 dedicated servers for one of my games as well. Probably only required if you want to do something with the full Steam client. 

> CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.

Steam internal, but can be ignored, has no impact on the ASA server.

> Failed to read /etc/machine-id, error Invalid argument.

Expected and can be ignored, since a unique machine id is not present in docker container images.

> wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

Expected and can be ignored, has no impact on the ASA server's functionality.

**Comment by heusmich** [comment] 2023-11-14 23:25
OK, then I can ignore all. :)
Thanks for the info.

As I already said, I will test the taming tomorrow again and then reply here.

**Comment by heusmich** [comment] 2023-11-15 10:47
Hi!
I tested it again now and tamed an Anky with Level 168, now it time is the correct time that is shown on Dododex.
So it seems that the DinoCharacterFoodDrainMultiplier setting was the problem.

Thanks for your help! :D

**Comment by mschnitzer** [comment] 2023-11-16 03:55
Sounds good, closing then :+1:

**Closed by mschnitzer** 2023-11-16 03:55 UTC
Labels: question
