### ISSUE TITLE
Can't connect to anything

### ISSUE THREAD

**Issue by DanKrones** [mschnitzer/ark-survival-ascended-linux-container-image#85] opened 2024-09-08 21:44 UTC
I can see that the server is up and running using Portainer.  I installed it on Docker on a headless server on my home network.  If I ssh into that machine and run nmap localhost -p 27020 I can see that port is open.  I have opened ports 7777 and 27020 on the firewall for the server.  I have forwarded port 27020 from my router to the server.  If we try to connect using the game console from a Windows machine on the local network, there is no response.  If I run your docker exec command from the server, I get a reply back showing the SessionName=ARK #442549 but when we look on the Steam Ark game list for unofficial servers we don't see this number listed.

**Comment by DanKrones** [comment] 2024-09-09 19:54
Forgive my ignorance (My daughter asked for my help to set up a server 
for her) and thank you for your attention to detail in my question.  I 
think I mean the In Game server browser.

Once the server was running, she tried to view it running in Steam from 
her computer.  She also tried to use the console from within her game 
that was running (under Steam).  It could not connect to port 27020.

If I log onto my linux server and do ifconfig, I get:

asanet: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
         inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
         inet6 fe80::42:69ff:fe1a:14c5  prefixlen 64  scopeid 0x20<link>
         ether 02:42:69:1a:14:c5  txqueuelen 0  (Ethernet)
         RX packets 1547  bytes 92684 (92.6 KB)
         RX errors 0  dropped 0  overruns 0  frame 0
         TX packets 287  bytes 12054 (12.0 KB)
         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

and if I ping 172.19.0.1 I get normal looking replies (no packet loss).

If we run ping on the Windows machine to 172.19.0.1 it also has normal 
replies (no packet loss).

-Dan

On 2024-09-09 11:11, Manuel Schnitzer wrote:

> When you say "Steam Ark game list", do you mean the Steam server 
> browser or the In Game server browser? There's no support to query the 
> status of the ARK server through Steam right now, this only works for 
> ASE.
> 
> Can you ping the internal server IP at all from your Windows PC?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/85#issuecomment-2338777496
[2]

**Comment by mschnitzer** [comment] 2024-09-12 11:38
Is the "Show player servers" checkbox checked?

**Comment by DanKrones** [comment] 2024-09-12 16:48
Is this what you mean by "Server Browser" ??

-Dan

On 2024-09-12 04:39, Manuel Schnitzer wrote:

> Is the "Show player servers" checkbox checked in the server browser? 
> This is required for self hosted servers.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/85#issuecomment-2346055334
[2]

**Comment by DanKrones** [comment] 2024-09-15 17:10
The picture was not added to my last emailed comment.  Here is the picture I meant to send when I was asking if this is what you meant by the server browser....

![33ac88c4](https://github.com/user-attachments/assets/b1833f6d-6d61-486f-8501-13f7fa38bbde)

**Comment by DanKrones** [comment] 2024-09-15 17:36
<img width="641" alt="image" src="https://github.com/user-attachments/assets/856c306f-6160-4914-8400-56776f1b6305">

**Comment by DanKrones** [comment] 2024-09-15 17:51
<img width="645" alt="image" src="https://github.com/user-attachments/assets/8b0cb41b-a5c8-4d29-a0ff-e2624e992e2b">

It looks like these 2 ports are needed to be open to run this game.  Especially port 7777.  If I look at the open ports on our server I see the following:

<img width="389" alt="image" src="https://github.com/user-attachments/assets/629e5de3-8fd5-4610-b1f2-9b10c2747127">

So it seems that 7777 is not open and 24020 is open.  Is this correct??

**Comment by DanKrones** [comment] 2024-09-15 17:57
Ignore my last comment.  It appears that UDP port 7777 is open:

<img width="389" alt="image" src="https://github.com/user-attachments/assets/6e12cd88-ae54-4673-8cc6-1f8d7eee2d84">

**Comment by mschnitzer** [comment] 2024-09-22 11:46
I wasn't able to investigate this further. I'm replying today or tomorrow again.

**Comment by DanKrones** [comment] 2024-09-25 03:01
I tried uninstalling and starting over again.  The command "docker-compose up -d" appeared to work:

root@saturn:/home/asa-server# docker compose up -d
WARN[0000] /home/asa-server/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 4/4
 ✔ set-permissions-1 Pulled                                                                                                                                                              4.3s
   ✔ 41e19e06a870 Pull complete                                                                                                                                                          2.4s
 ✔ asa-server-1 Pulled                                                                                                                                                                   8.2s
   ✔ 19a61db28155 Pull complete                                                                                                                                                          6.7s
[+] Running 8/8
 ✔ Network asa-server_asa-network            Created                                                                                                                                     0.2s
 ✔ Network asa-server_default                Created                                                                                                                                     0.2s
 ✔ Volume "asa-server_steamcmd-1"            Created                                                                                                                                     0.0s
 ✔ Volume "asa-server_server-files-1"        Created                                                                                                                                     0.0s
 ✔ Volume "asa-server_cluster-shared"        Created                                                                                                                                     0.0s
 ✔ Volume "asa-server_steam-1"               Created                                                                                                                                     0.0s
 ✔ Container asa-server-set-permissions-1-1  Started                                                                                                                                     0.7s
 ✔ Container asa-server-1                    Started     
 
 And then I did your "docker logs asa-server-1" and got this:
 
 root@saturn:/home/asa-server# docker logs -f asa-server-1
--2024-09-24 19:47:52--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'steamcdn-a.akamaihd.net'
tar (child): steamcmd_linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/usr/bin/start_server: line 17: ./steamcmd.sh: No such file or directory
Downloading Proton version 8-21... This might take a while
--2024-09-24 19:48:00--  https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-21/GE-Proton8-21.tar.gz
Resolving github.com (github.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'github.com'

And a bunch more unable to resolve host errors and after all this was printed, the container was no longer running.  I restarted it and tried again but got the same result.

This is strange because it previously installed the game and was running.  Do have any suggestions?

**Comment by DanKrones** [comment] 2024-09-25 04:12
okay, this is me learning about docker.  I had to change the yml file so it supports host networking.  As soon as I did that the docker had connection to the internet and loaded.  And now we can connect to it from the game and it plays correctly.

**Comment by mschnitzer** [comment] 2024-09-26 15:36
So the issue is solved? Can we close this issue?

**Comment by DanKrones** [comment] 2024-09-27 15:17
Yes the issue is solved.  Thank you so much for your help!

-Dan

On 2024-09-26 08:36, Manuel Schnitzer wrote:

> So the issue is solved? Can we close this issue?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/85#issuecomment-2377313498
[2]

**Closed** 2024-09-27 18:44 UTC
Labels: question
