### ISSUE TITLE
Startup message and unable to connect

### ISSUE THREAD

**Issue by padesmo** [mschnitzer/ark-survival-ascended-linux-container-image#41] opened 2024-01-03 10:49 UTC
Hey` i the docker just downloaded the APP and started it, Server is also visable in ASA but im unable to connect

`Success! App '2430930' fully installed.`
`Starting the ARK: Survival Ascended dedicated server...`
`Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50`
`Proton: Upgrading prefix from None to GE-Proton8-21 (/home/gameserver/server-files/steamapps/compatdata/2430930/)`
`fsync: up and running.`
`Failed to read /etc/machine-id, error Invalid argument.`
`wine: RLIMIT_NICE is <= 20, unable to use setpriority safely`

**Comment by scottrbaxter** [comment] 2024-01-04 04:49
same issue. have you found a solution yet?

**Comment by padesmo** [comment] 2024-01-04 09:36
> same issue. have you found a solution yet?

nope, i setup a Windows Server with Windows Pro now and used another tool

**Comment by mschnitzer** [comment] 2024-01-04 15:29
The messages you are seeing can be ignored. There were already some closed issues regarding this since it confuses some people.

The reason you cannot connect is likely caused by other factors. But I need more information on your set up (distribution, VM or baremetal host, home setup, etc.).

Also your `docker-compose.yml` is helpful.

**Comment by scottrbaxter** [comment] 2024-01-04 16:55
Initial test was Docker for Desktop on macOS Sonoma. Intel Mac Mini (2018) 6 core w/ 64GB ram. I had setup port forwarding for 7777 (tcp and udp) but never found any traffic attempts to access it from WAN in the logs. I'm unsure of how this server relationship is determined - this is my first attempt at getting a server connected upstream. The container seems to run ok up until the errors that were shared above. my experience was identical. I never got to the point where the server session id would be provided in the logs. TBH, i'd prefer to simply expose this as a variable and be permitted to assign my own session id... but for now, i'd be happy with just figuring out why this is an issue.

Also, I did switch the volume mounts to bind mounts so that i could parse the internal logging easier, which i'd recommend you doing in the future if you're not going to send all of the necessary logs through `docker logs`, but didn't come across any obvious reasons to not work as expected.

Curious, is there any sort of validation/testing that can be easily done ahead of attempting to find the session in-game?

**Comment by mschnitzer** [comment] 2024-01-04 17:22
You only need to forward UDP 7777 - it doesn't use TCP. Where did you forward the ports? In your router?

What do you mean by session id? The server name? If yes, the session name is auto generated on the first server start and is explained here: https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#4-first-server-start

It can be changed by accessing the server files in the docker volume:
```
[...]/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini
```

Furthermore, did you check the "Show player servers" checkbox on the bottom right of the server browser? They introduced this checkbox just recently and made it so that non-Nitrado servers are hidden by default from the server browser. If the checkbox was the problem, don't feel too bad about it, several people ran into this already since it was silently introduced.

**Comment by mschnitzer** [comment] 2024-01-14 10:04
Is this still an issue or can we close it?

**Comment by mschnitzer** [comment] 2024-01-18 21:18
Closing. Please reopen if it's still an issue.

**Closed by mschnitzer** 2024-01-18 21:18 UTC
Labels: question
